# Generated by Django 5.0.1 on 2024-03-12 11:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id_conge', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('delete_date', models.DateTimeField(null=True)),
                ('update_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'Conge',
            },
        ),
        migrations.CreateModel(
            name='CRA',
            fields=[
                ('id_cra', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_cra', models.DateField(auto_now_add=True)),
                ('abscence', models.BooleanField(default=True)),
                ('astreintes', models.BooleanField(default=True)),
                ('mission', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Compte_rendu_activite',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id_goupe', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_users', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Type_collaborateur',
            },
        ),
    ]
