# Generated by Django 5.0.1 on 2024-03-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postuler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=40)),
                ('compagny', models.CharField(max_length=50)),
                ('cv', models.FileField(upload_to='curriculum_vitae')),
                ('message', models.CharField(max_length=100)),
                ('type_candidat', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'postuler',
            },
        ),
    ]
