# Generated by Django 5.0.1 on 2024-03-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portail_web', '0002_postuler_non_spontaner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postuler',
            name='non_spontaner',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='postuler',
            name='type_candidat',
            field=models.CharField(max_length=50),
        ),
    ]
