# Generated by Django 5.0.1 on 2024-06-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portail_web', '0004_alter_postuler_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postuler',
            name='offre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
